---

- name: Install systemd Service Files
  become: true
  ansible.builtin.template:
    src: ../templates/{{ item }}.j2
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - mastodon-web.service
    - mastodon-sidekiq.service
    - mastodon-streaming.service

- name: Start and enable services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - mastodon-web
    - mastodon-sidekiq
    - mastodon-streaming


